server {
    listen 80;
    server_name localhost;

    # 1. Rota para o Frontend (Arquivos Estáticos)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Rota para a API do Backend (Proxy Reverso)
    # Qualquer chamada para /equipamentos ou /auth é encaminhada internamente para o Express rodando no Bun
    location ~ ^/(equipamentos|auth) {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
