services:
  backend:
    image: joaovitorbr/avaliacao_3_dsw2026_1:latest
    container_name: dsw-backend
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
    networks:
      - HDSwarmNet
    deploy:
      labels:
        - "traefik.enable=true"
        # Configura o Traefik para responder no seu domínio correto
        - "traefik.http.routers.dsw-app.rule=Host(`crud-equipamentos.hyperdynamis.com`)"
        - "traefik.http.routers.dsw-app.entrypoints=websecure"
        - "traefik.http.routers.dsw-app.tls=true"
        - "traefik.http.routers.dsw-app.tls.certresolver=letsencryptresolver" # resolvedor de SSL do seu Traefik
        - "traefik.http.services.dsw-app.loadbalancer.server.port=3000"

networks:
  HDSwarmNet:
    external: true
